# Software Statement ID
ssid: <*>

# Organisation ID
org_id: <*>

# Request Issuer
iss: <*>

# These should match the key/certificate pair you put inside the cert directory
signing_key_id: <*>
transport_key_id: <*>

# openid is required
# the rest of the scopes can be adjusted according to your needs
scope: openid accounts payments

# Registered URIs the TPP will use to interact with the ASPSP AS
redirect_uris:
  - https://example.com/oauth/callback
